name: segdiff
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - bottleneck=1.3.5=py38h7deecbd_0
  - brotli=1.0.9=h5eee18b_7
  - brotli-bin=1.0.9=h5eee18b_7
  - brotli-python=1.0.9=py38h6a678d5_7
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.3.11=h06a4308_0
  - certifi=2024.2.2=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cloudpickle=2.2.1=py38h06a4308_0
  - cryptography=42.0.5=py38hdda0065_1
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.1.1=hb139c0e_13
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - cytoolz=0.12.0=py38h5eee18b_0
  - dask-core=2023.4.1=py38h06a4308_0
  - dbus=1.13.18=hb2f20db_0
  - expat=2.5.0=h6a678d5_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.14.1=h52c9d5c_1
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2023.9.2=py38h06a4308_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py38h06a4308_0
  - imageio=2.31.4=py38h06a4308_0
  - importlib-metadata=6.0.0=py38h06a4308_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - jinja2=3.1.3=py38h06a4308_0
  - joblib=1.2.0=py38h06a4308_0
  - jpeg=9e=h5eee18b_1
  - kiwisolver=1.4.4=py38h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lazy_loader=0.3=py38h06a4308_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.0.9=h5eee18b_7
  - libbrotlidec=1.0.9=h5eee18b_7
  - libbrotlienc=1.0.9=h5eee18b_7
  - libcblas=3.9.0=16_linux64_mkl
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcups=2.4.2=h2d74bed_1
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=13.2.0=h77fa898_6
  - libgfortran-ng=13.2.0=h69a702a_6
  - libgfortran5=13.2.0=h43f5ff8_6
  - libglib=2.78.4=hdc74915_0
  - libgomp=13.2.0=h77fa898_6
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm14=14.0.6=hdb19cb5_3
  - libnpp=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.17=hdbd6064_0
  - libstdcxx-ng=13.2.0=hc0a3c3a_6
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=hfa300c1_0
  - libxml2=2.9.14=h74e7548_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib=3.4.3=py38h06a4308_0
  - matplotlib-base=3.4.3=py38hbbc1b5f_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpi=1.0=openmpi
  - mpi4py=3.1.2=py38h3e8e7aa_0
  - mpmath=1.3.0=py38h06a4308_0
  - munkres=1.1.4=py_0
  - mysql=5.7.24=h721c034_2
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - nomkl=2.0=0
  - numexpr=2.8.4=py38hb2af0cf_101
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openmpi=4.1.6=hc5af2df_101
  - openssl=3.0.13=h7f8727e_1
  - packaging=23.1=py38h06a4308_0
  - pandas=1.5.3=py38h417a72b_0
  - partd=1.4.1=py38h06a4308_0
  - pcre=8.45=h295c915_0
  - pcre2=10.42=hebb0a14_1
  - pillow=10.3.0=py38h5eee18b_0
  - pip=21.2.4=py38h06a4308_0
  - platformdirs=3.10.0=py38h06a4308_0
  - ply=3.11=py38_0
  - pooch=1.7.0=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=24.0.0=py38h06a4308_0
  - pyparsing=3.0.9=py38h06a4308_0
  - pyqt=5.15.10=py38h6a678d5_0
  - pyqt5-sip=12.13.0=py38h5eee18b_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=2.3.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py38h06a4308_0
  - pywavelets=1.4.1=py38h5eee18b_0
  - pyyaml=6.0.1=py38h5eee18b_0
  - qt=5.15.9=h06a4308_0
  - qt-main=5.15.2=h7358343_9
  - qt-webengine=5.15.9=hd2b0992_4
  - readline=8.2=h5eee18b_0
  - requests=2.31.0=py38h06a4308_0
  - scikit-image=0.20.0=py38h6a678d5_0
  - scikit-learn=0.24.2=py38ha9443f7_0
  - scipy=1.9.1=py38hea3f02b_0
  - seaborn=0.11.2=pyhd3eb1b0_0
  - setuptools=68.0.0=py38h06a4308_0
  - sip=6.7.12=py38h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h5eee18b_0
  - sympy=1.12=py38h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py38h06a4308_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=2.3.0=py38_cu118
  - torchtriton=2.3.0=py38
  - torchvision=0.18.0=py38_cu118
  - tornado=6.3.3=py38h5eee18b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - typing_extensions=4.7.1=py38h06a4308_0
  - urllib3=1.26.18=py38h06a4308_0
  - wheel=0.41.2=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.11.0=py38h06a4308_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hc292b87_2
  - pip:
      - blobfile==1.2.3
      - cython==3.0.10
      - filelock==3.14.0
      - gitpython==3.1.24
      - h5py==3.4.0
      - imagecodecs==2021.11.20
      - kornia==0.5.11
      - opencv-python==4.5.1.48
      - pycocotools==2.0.2
      - pycryptodomex==3.20.0
      - xmltodict==0.12.0
